"""One-off script: reads a chapter's theory YAML plus its syllabus, and
writes a SQL seed file that inserts lesson rows into the `lessons` table
(20260930000000_theory_lessons.sql). Mirrors seed_mission.py's shape.

Run (from repo root): python -m content.pipeline.seed_theory
Writes: backend/supabase/seed/005_surface_area_volume_theory.sql
"""
from __future__ import annotations

import json
from pathlib import Path

import yaml

from .issues import Issues
from .syllabus import load as load_syllabus
from .types import REGISTRY
from .types.lesson import validate_lesson

REPO_ROOT = Path(__file__).resolve().parents[2]
THEORY_YAML = REPO_ROOT / "content/questions/cbse/9/maths/surface_area_volume_theory.yaml"
SYLLABUS_YAML = REPO_ROOT / "content/syllabus/cbse/9/maths.yaml"
OUTPUT_SQL = REPO_ROOT / "backend/supabase/seed/005_surface_area_volume_theory.sql"


def _sql_str(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def _sql_str_or_null(value: str | None) -> str:
    return "null" if value is None else _sql_str(value)


def _load_yaml(path: Path) -> dict:
    with open(path, encoding="utf-8") as f:
        return yaml.safe_load(f)


def generate_sql(theory_path: Path, syllabus_path: Path) -> str:
    theory = _load_yaml(theory_path)
    lessons = theory["lessons"]

    issues = Issues()
    syllabus = load_syllabus(syllabus_path, issues, set(REGISTRY))
    if issues.errors:
        raise ValueError(f"syllabus failed to load: {issues.errors}")
    seen_ids: set[str] = set()
    for lesson in lessons:
        where = lesson.get("id", "<no id>")
        if where in seen_ids:
            issues.error(where, f"duplicate lesson id '{where}'")
        seen_ids.add(where)
        validate_lesson(lesson, syllabus, issues, where)
    if issues.errors:
        raise ValueError(f"lesson content invalid, refusing to seed: {issues.errors}")

    lines = [
        "-- Generated by content/pipeline/seed_theory.py — do not hand-edit.",
        "-- Seeds lesson rows for the surface_area_volume chapter's theory content.",
        "",
        "begin;",
        "",
        "insert into lessons (id, concept_id, title, body, hook_kind, hook, try_it, sort_order) values",
    ]

    rows = []
    for lesson in lessons:
        rows.append(
            "  (" + ", ".join([
                _sql_str(lesson["id"]),
                _sql_str(lesson["concept_id"]),
                _sql_str(lesson["title"]),
                _sql_str(lesson["body"]),
                _sql_str(lesson["hook_kind"]),
                _sql_str(lesson["hook"]),
                _sql_str_or_null(lesson.get("try_it")),
                str(lesson["sort_order"]),
            ]) + ")"
        )
    lines.append(",\n".join(rows))
    # Upsert, not a plain insert: once students have read a lesson,
    # theory_progress references it, so a wording fix must update the row
    # in place rather than delete-and-reinsert.
    lines.append("on conflict (id) do update set")
    cols = ["concept_id", "title", "body", "hook_kind", "hook", "try_it", "sort_order"]
    lines.append(",\n".join(f"  {c} = excluded.{c}" for c in cols) + ";")
    lines.append("")
    lines.append("commit;")
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    sql = generate_sql(THEORY_YAML, SYLLABUS_YAML)
    OUTPUT_SQL.write_text(sql, encoding="utf-8")
    print(f"Wrote {OUTPUT_SQL}")


if __name__ == "__main__":
    main()
