"""Generates the course-structure seed from the syllabus and the Trial YAML:
the syllabus's units, every syllabus chapter (in syllabus order, linked to its
unit) and each Trial level's `why_after_previous` text.

Idempotent: safe on the live database (seeds 001-006 already applied) and on a
fresh one. Upserts units and chapters, and updates question bodies in place.

Run (from repo root): python -m content.pipeline.seed_course
Writes: backend/supabase/seed/007_course_structure.sql
"""
from __future__ import annotations

from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
SYLLABUS_YAML = REPO_ROOT / "content/syllabus/cbse/9/maths.yaml"
MISSION_YAML = REPO_ROOT / "content/questions/cbse/9/maths/surface_area_volume.yaml"
OUTPUT_SQL = REPO_ROOT / "backend/supabase/seed/007_course_structure.sql"

SUBJECT_ID = "cbse_9_maths"

# Chapters created before the syllabus file existed kept their old ids:
# renaming a chapter id breaks the concepts and level_progress foreign keys
# (see 20260927000000_m9_maths_id_convention_and_new_chapters.sql). Every
# other syllabus chapter id is used as the database id unchanged.
LEGACY_CHAPTER_IDS = {
    "number_system": "num",
    "coordinate_geometry": "coord",
    "polynomials": "poly",
}

_TAG = "$wap$"


def _sql_str(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def _text_literal(value: str) -> str:
    # A tagged dollar quote: the text contains LaTeX ($...$), and the tag
    # makes an accidental "$$" inside it harmless.
    if _TAG in value:
        raise ValueError(f"text contains the quote tag {_TAG}: {value!r}")
    return f"{_TAG}{value}{_TAG}"


def _load_yaml(path: Path) -> dict:
    with open(path, encoding="utf-8") as f:
        return yaml.safe_load(f)


def unit_id(yaml_unit: str) -> str:
    return f"{SUBJECT_ID}.{yaml_unit}"


def chapter_db_id(yaml_chapter: str) -> str:
    return LEGACY_CHAPTER_IDS.get(yaml_chapter, yaml_chapter)


def _number(value) -> str:
    return str(int(value)) if float(value).is_integer() else str(value)


def generate_sql(syllabus_path: Path, mission_path: Path) -> str:
    syllabus = _load_yaml(syllabus_path)
    mission = _load_yaml(mission_path)

    lines = [
        "-- Generated by content/pipeline/seed_course.py — do not hand-edit.",
        "-- Units and chapters from content/syllabus/cbse/9/maths.yaml, and each",
        "-- Trial level's why_after_previous. Safe to re-run.",
        "",
        "begin;",
        "",
        "insert into units (id, subject_id, name, marks, sort_order) values",
    ]
    unit_rows = [
        f"  ({_sql_str(unit_id(u['id']))}, {_sql_str(SUBJECT_ID)}, {_sql_str(u['name'])}, "
        f"{_number(u['marks'])}, {i})"
        for i, u in enumerate(syllabus["units"], start=1)
    ]
    lines.append(",\n".join(unit_rows))
    lines.append("on conflict (id) do update set")
    lines.append("  name = excluded.name, marks = excluded.marks, sort_order = excluded.sort_order;")
    lines.append("")

    lines.append("insert into chapters (id, subject_id, name, board_weight, sort_order, unit_id) values")
    chapter_rows = [
        f"  ({_sql_str(chapter_db_id(ch['id']))}, {_sql_str(SUBJECT_ID)}, {_sql_str(ch['name'])}, "
        f"{_number(ch['board_weight_marks'])}, {i}, {_sql_str(unit_id(ch['unit']))})"
        for i, ch in enumerate(syllabus["chapters"], start=1)
    ]
    lines.append(",\n".join(chapter_rows))
    lines.append("on conflict (id) do update set")
    lines.append(
        "  name = excluded.name, board_weight = excluded.board_weight, "
        "sort_order = excluded.sort_order, unit_id = excluded.unit_id;"
    )
    lines.append("")

    for q in mission["questions"]:
        why = q.get("why_after_previous")
        if not why:
            continue
        lines.append(
            "update questions set body = body || jsonb_build_object('whyAfterPrevious', "
            f"{_text_literal(why)}::text) where id = {_sql_str(q['id'])};"
        )
    lines.append("")
    lines.append("commit;")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    OUTPUT_SQL.write_text(generate_sql(SYLLABUS_YAML, MISSION_YAML), encoding="utf-8")
    print(f"Wrote {OUTPUT_SQL}")


if __name__ == "__main__":
    main()
